id: PBB16FEBB
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS23418
  title: དགེ་ལྡན་པའི་ལམ་རིམ་དང་སྙན་བརྒྱུད་ཀྱི་ཆོས་སྐོར།
  volumes:
    c984b49d22aa48aba61feb5fc3046a54:
      image_group_id: I8LS23420
      title: ''
      base_file: v001.txt
  author: ''
